{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyM3SqWoh8oO476DzYx5I1aE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/pumps69-cmyk/kyomoto/blob/main/App.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import openpyxl\n",
        "import zipfile\n",
        "import os\n",
        "import re\n",
        "import datetime\n",
        "from pathlib import Path\n",
        "\n",
        "# Configuración de la página web\n",
        "st.set_page_config(page_title=\"Kyomoto Engine v6.0\", page_icon=\"⚡\", layout=\"centered\")\n",
        "\n",
        "st.markdown(\"<h1 style='text-align: center;'>⚡ KYOMOTO (京本) - ENGINE v6.0 ⚡</h1>\", unsafe_allow_html=True)\n",
        "st.markdown(\"---\")\n",
        "\n",
        "def limpiar_texto(texto):\n",
        "    return re.sub(r'[^a-z0-9]', '', str(texto).lower())\n",
        "\n",
        "def parsear_sql_estricto(sql_texto):\n",
        "    tablas = {}\n",
        "    orden_tablas = []\n",
        "    db_nombre = \"jdm_motores_db\"\n",
        "\n",
        "    match_db = re.search(r'(?:CREATE DATABASE|USE)\\s+`?([a-zA-Z0-9_]+)`?', sql_texto, flags=re.IGNORECASE)\n",
        "    if match_db: db_nombre = match_db.group(1)\n",
        "\n",
        "    fragmentos = re.split(r'CREATE TABLE', sql_texto, flags=re.IGNORECASE)[1:]\n",
        "    for frag in fragmentos:\n",
        "        match_nombre = re.search(r'(?:IF NOT EXISTS\\s+)?`?([a-zA-Z0-9_]+)`?\\s*\\(', frag, flags=re.IGNORECASE)\n",
        "        if match_nombre:\n",
        "            nombre = match_nombre.group(1)\n",
        "            orden_tablas.append(nombre)\n",
        "            tablas[nombre] = {'columnas': [], 'pk': [], 'fk': []}\n",
        "\n",
        "            bloque = frag[match_nombre.end():frag.rfind(')')]\n",
        "            lineas = bloque.split(',')\n",
        "\n",
        "            for linea in lineas:\n",
        "                linea = linea.strip()\n",
        "                if not linea: continue\n",
        "\n",
        "                if re.match(r'PRIMARY KEY', linea, re.IGNORECASE):\n",
        "                    pk_match = re.search(r'\\(`?([^`)]+)`?\\)', linea)\n",
        "                    if pk_match: tablas[nombre]['pk'].append(pk_match.group(1))\n",
        "                elif re.match(r'(CONSTRAINT.*)?FOREIGN KEY', linea, re.IGNORECASE):\n",
        "                    fk_match = re.search(r'FOREIGN KEY\\s*\\(`?([^`)]+)`?\\)\\s*REFERENCES\\s*`?([^`\\s]+)`?\\s*\\(`?([^`)]+)`?\\)', linea, re.IGNORECASE)\n",
        "                    if fk_match:\n",
        "                        tablas[nombre]['fk'].append({'columna': fk_match.group(1), 'tabla_ref': fk_match.group(2), 'col_ref': fk_match.group(3)})\n",
        "                elif not re.match(r'(UNIQUE|KEY|CONSTRAINT)\\b', linea, re.IGNORECASE):\n",
        "                    col_match = re.match(r'`?([a-zA-Z0-9_]+)`?', linea)\n",
        "                    if col_match: tablas[nombre]['columnas'].append(col_match.group(1))\n",
        "\n",
        "    return orden_tablas, tablas, db_nombre\n",
        "\n",
        "def verificar_coincidencia_tablas(tablas_sql, datos_cargados):\n",
        "    tablas_sql_set = set(tablas_sql)\n",
        "    tablas_datos_set = set(datos_cargados.keys())\n",
        "    return tablas_sql_set.issubset(tablas_datos_set) or tablas_datos_set.issubset(tablas_sql_set)\n",
        "\n",
        "# =====================================================================\n",
        "# PASO 1: PROTOCOLO HAYAKAWA 1 (Seguridad)\n",
        "# =====================================================================\n",
        "st.subheader(\"🔒 [PROTOCOLO HAYAKAWA 1]\")\n",
        "frase_input = st.text_input(\"Responde la pregunta de seguridad: *dame tu coleta la quiero tela exijo sera mi…*\", type=\"password\")\n",
        "\n",
        "if frase_input:\n",
        "    acceso_total = (limpiar_texto(frase_input) == limpiar_texto(\"Mi reliquia familiar\"))\n",
        "\n",
        "    if acceso_total:\n",
        "        st.success(\"🔓 ¡Correcto! Acceso total concedido al núcleo de Kyomoto.\")\n",
        "        modos_disponibles = [\n",
        "            '1. Crear Plantilla Estructural de Excel',\n",
        "            '2. Esenciales: Inserts + CSV/Excel + Instructivos',\n",
        "            '3. MEGA PRO: Todo + CRUD + Auditoría y Seguridad'\n",
        "        ]\n",
        "    else:\n",
        "        st.warning(\"🚨 Respuesta incorrecta. Acceso restringido ÚNICAMENTE al Modo Básico.\")\n",
        "        modos_disponibles = [\n",
        "            '1. Crear Plantilla Estructural de Excel (Única opción disponible)'\n",
        "        ]\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    st.subheader(\"⚙ CONFIGURACIÓN DE OPERACIÓN\")\n",
        "\n",
        "    modo_elegido = st.selectbox(\"Selecciona el Modo:\", modos_disponibles)\n",
        "\n",
        "    tipo_insercion_txt = st.selectbox(\n",
        "        \"Tipo de Inserción SQL:\",\n",
        "        ['INSERT INTO (Estándar)', 'INSERT IGNORE (Omite duplicados)', 'REPLACE INTO (Sobrescribe duplicados)']\n",
        "    )\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    st.subheader(\"📁 CARGA DE ARCHIVOS\")\n",
        "    st.info(\"💡 Sube tu archivo `.sql` (o `.txt`) y tus archivos de datos (`.xlsx`, `.csv`) aquí mismo sin restricciones desde tu celular o PC.\")\n",
        "\n",
        "    archivos_cargados = st.file_uploader(\"Seleccionar Archivos\", accept_multiple_files=True, type=['sql', 'txt', 'xlsx', 'xls', 'csv'])\n",
        "\n",
        "    if st.button(\"🚀 Confirmar y Ejecutar Proceso\", type=\"primary\"):\n",
        "        if not archivos_cargados:\n",
        "            st.error(\"❌ Error: Debes subir al menos el archivo .sql guía.\")\n",
        "        else:\n",
        "            # Procesar archivos subidos\n",
        "            uploaded_dict = {}\n",
        "            for archivo in archivos_cargados:\n",
        "                uploaded_dict[archivo.name] = archivo.read()\n",
        "\n",
        "            carpeta_salida = \"kyomoto_output\"\n",
        "            if os.path.exists(carpeta_salida): shutil.rmtree(carpeta_salida)\n",
        "            os.makedirs(carpeta_salida, exist_ok=True)\n",
        "\n",
        "            sql_texto = \"\"\n",
        "            archivos_csv_subidos = []\n",
        "            excel_cargado = None\n",
        "\n",
        "            cmd_sql = \"INSERT INTO\"\n",
        "            if \"IGNORE\" in tipo_insercion_txt: cmd_sql = \"INSERT IGNORE INTO\"\n",
        "            elif \"REPLACE\" in tipo_insercion_txt: cmd_sql = \"REPLACE INTO\"\n",
        "\n",
        "            for nombre, contenido in uploaded_dict.items():\n",
        "                if nombre.endswith('.sql') or nombre.endswith('.txt'):\n",
        "                    try: decodificado = contenido.decode('utf-8')\n",
        "                    except UnicodeDecodeError: decodificado = contenido.decode('latin-1')\n",
        "\n",
        "                    if nombre.endswith('.sql') or \"CREATE TABLE\" in decodificado.upper():\n",
        "                        if not sql_texto:\n",
        "                            sql_texto = decodificado\n",
        "\n",
        "                elif nombre.endswith(('.xlsx', '.xls')):\n",
        "                    excel_cargado = nombre\n",
        "                    with open(nombre, 'wb') as f: f.write(contenido)\n",
        "                elif nombre.endswith('.csv'):\n",
        "                    archivos_csv_subidos.append(nombre)\n",
        "                    with open(nombre, 'wb') as f: f.write(contenido)\n",
        "\n",
        "            modo_id = modo_elegido[0] # Extraer el número del modo (1, 2 o 3)\n",
        "\n",
        "            if modo_id == \"1\":\n",
        "                if not sql_texto:\n",
        "                    st.error(\"❌ Error: Se requiere obligatoriamente el archivo .sql guía.\")\n",
        "                else:\n",
        "                    orden_t, dic_t, _ = parsear_sql_estricto(sql_texto)\n",
        "                    ruta_plantilla = \"Kyomoto_Plantilla_Estructural.xlsx\"\n",
        "                    with pd.ExcelWriter(ruta_plantilla, engine='openpyxl') as writer:\n",
        "                        for t in orden_t:\n",
        "                            pd.DataFrame(columns=dic_t[t]['columnas']).to_excel(writer, sheet_name=t, index=False)\n",
        "\n",
        "                    st.success(\"✅ Plantilla estructural generada con éxito.\")\n",
        "                    with open(ruta_plantilla, \"rb\") as f:\n",
        "                        st.download_button(\"📥 Descargar Plantilla Excel\", f, file_name=\"Kyomoto_Plantilla_Estructural.xlsx\")\n",
        "            else:\n",
        "                if not sql_texto:\n",
        "                    st.error(\"❌ Error crítico: Se necesita el archivo .sql para validar estructuras.\")\n",
        "                else:\n",
        "                    datos_en_memoria = {}\n",
        "                    if excel_cargado:\n",
        "                        datos_en_memoria = pd.read_excel(excel_cargado, sheet_name=None)\n",
        "                    elif archivos_csv_subidos:\n",
        "                        for arch in archivos_csv_subidos:\n",
        "                            datos_en_memoria[Path(arch).stem] = pd.read_csv(arch)\n",
        "\n",
        "                    orden_t, dic_t, nombre_db = parsear_sql_estricto(sql_texto)\n",
        "                    estructuras_ok = verificar_coincidencia_tablas(orden_t, datos_en_memoria)\n",
        "\n",
        "                    if not estructuras_ok:\n",
        "                        st.warning(\"⚠ [ALERTA DE ESTRUCTURA]: Los nombres de tus tablas no coinciden con el SQL guía.\")\n",
        "                        clave_rescate = st.text_input(\"🔒 [Protocolo Hayakawa 2] - Inscribe la clave de rescate:\", type=\"password\")\n",
        "\n",
        "                        if clave_rescate:\n",
        "                            if clave_rescate == \"Easy revenge\":\n",
        "                                st.success(\"🔓 [Protocolo Hayakawa 2]: Clave correcta. Kyomoto ha corregido las estructuras.\")\n",
        "                                datos_mapeados = {}\n",
        "                                for t_sql in orden_t:\n",
        "                                    for t_csv, df in datos_en_memoria.items():\n",
        "                                        if limpiar_texto(t_sql) in limpiar_texto(t_csv) or limpiar_texto(t_csv) in limpiar_texto(t_sql):\n",
        "                                            datos_mapeados[t_sql] = df\n",
        "                                if not datos_mapeados:\n",
        "                                    datos_mapeados = datos_en_memoria\n",
        "\n",
        "                                # Ejecutar proceso final\n",
        "                                zip_path = generar_kit_final(orden_t, dic_t, nombre_db, datos_mapeados, sql_texto, cmd_sql, modo_id, carpeta_salida)\n",
        "                                with open(zip_path, \"rb\") as f:\n",
        "                                    st.download_button(\"📦 Descargar Kit Kyomoto Ecosystem (.zip)\", f, file_name=\"Kyomoto_Ecosystem.zip\", mime=\"application/zip\")\n",
        "                            else:\n",
        "                                st.error(\"🚨 Clave incorrecta. Sistema bloqueado.\")\n",
        "                    else:\n",
        "                        zip_path = generar_kit_final(orden_t, dic_t, nombre_db, datos_en_memoria, sql_texto, cmd_sql, modo_id, carpeta_salida)\n",
        "                        st.success(\"✅ ¡Kit Kyomoto (京本) generado con éxito!\")\n",
        "                        with open(zip_path, \"rb\") as f:\n",
        "                            st.download_button(\"📦 Descargar Kit Kyomoto Ecosystem (.zip)\", f, file_name=\"Kyomoto_Ecosystem.zip\", mime=\"application/zip\")\n",
        "\n",
        "def generar_kit_final(orden_t, dic_t, nombre_db, datos_en_memoria, sql_texto, cmd_sql, modo_elegido, carpeta_salida):\n",
        "    timestamp = datetime.datetime.now().strftime(\"%Y-%m-%d_%H-%M-%S\")\n",
        "    inserts_totales = []\n",
        "\n",
        "    for t, df in datos_en_memoria.items():\n",
        "        if t in dic_t:\n",
        "            cols = \", \".join(df.columns)\n",
        "            lineas_tabla = [f\"\\n-- INSERTS: {t}\"]\n",
        "            for _, fila in df.iterrows():\n",
        "                vals = [\"NULL\" if pd.isna(v) else (str(v) if isinstance(v, (int, float)) else f\"'{str(v).replace(chr(39), chr(39)+chr(39))}'\") for v in fila]\n",
        "                lineas_tabla.append(f\"{cmd_sql} {t} ({cols}) VALUES ({', '.join(vals)});\")\n",
        "            inserts_totales.append(\"\\n\".join(lineas_tabla))\n",
        "\n",
        "    inserts_texto = \"\\n\".join(inserts_totales)\n",
        "\n",
        "    with open(f\"{carpeta_salida}/01_solo_inserts.sql\", 'w', encoding='utf-8') as f: f.write(inserts_texto)\n",
        "    with open(f\"{carpeta_salida}/02_BACKUP_MAESTRO_{timestamp}.sql\", 'w', encoding='utf-8') as f:\n",
        "        f.write(sql_texto + \"\\n\\n\" + inserts_texto)\n",
        "\n",
        "    with open(f\"{carpeta_salida}/03_INSTRUCTIVO_IMPORTACION.txt\", 'w', encoding='utf-8') as f:\n",
        "        f.write(f\"BASE DE DATOS: {nombre_db}\\nORDEN ESTRICTO DE IMPORTACION:\\n\" + \"\\n\".join([f\"{i}. {t}\" for i, t in enumerate(orden_t, 1)]))\n",
        "\n",
        "    if modo_elegido == \"3\":\n",
        "        os.makedirs(f\"{carpeta_salida}/07_mini_php_crud\", exist_ok=True)\n",
        "        with open(f\"{carpeta_salida}/07_mini_php_crud/index.php\", 'w', encoding='utf-8') as f:\n",
        "            f.write(f'''<!DOCTYPE html>\n",
        "<html lang=\"es\">\n",
        "<head><meta charset=\"UTF-8\"><title>Kyomoto CRUD - {nombre_db}</title></head>\n",
        "<body>\n",
        "    <h1>京本 CRUD - {nombre_db}</h1>\n",
        "    <form method=\"GET\">\n",
        "        <input type=\"text\" name=\"buscar\" placeholder=\"Consulta...\">\n",
        "        <button type=\"submit\">Buscar</button>\n",
        "    </form>\n",
        "    <?php\n",
        "    if (isset($_GET['buscar'])) {{\n",
        "        $b = trim($_GET['buscar']);\n",
        "        if ($b === 'lock_back') {{\n",
        "            echo '<p style=\"color:red; font-weight:bold;\">a pumps le gustan los frutilupis</p>';\n",
        "        }} else {{\n",
        "            echo \"<p>Resultados para: \" . htmlspecialchars($b) . \"</p>\";\n",
        "        }}\n",
        "    }}\n",
        "    ?>\n",
        "</body>\n",
        "</html>''')\n",
        "\n",
        "    shutil.make_archive(\"Kyomoto_Ecosystem\", 'zip', carpeta_salida)\n",
        "    return \"Kyomoto_Ecosystem.zip\"\n"
      ],
      "metadata": {
        "id": "mWsGdKqbS5y8"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}